apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::570753532112:role/eksctl-brain-tasks-cluster-nodegro-NodeInstanceRole-oCJp5CfM1pib
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::570753532112:role/service-role/mycodebuild00
      username: build
