version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 570753532112.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=570753532112.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo REPOSITORY_URI=$REPOSITORY_URI
      - echo IMAGE_TAG=$IMAGE_TAG

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - echo "Listing Docker images after build..."
      - docker images

  post_build:
    commands:
      - echo Build completed on `date`
      - echo "Listing Docker images before push..."
      - docker images
      - echo Pushing image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG || { echo "Docker push failed"; exit 1; }
      - echo Writing image definition file...
      - printf '[{"name":"brain-tasks-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files: 
    - imagedefinitions.json
