version: 0.2
env:
  variables:
    REPOSITORY_NAME: brain-tasks-app
    AWS_DEFAULT_REGION: ap-south-1

phases:
  pre_build:
    commands:
      - echo "Ensure ECR repos exist"
      - aws ecr create-repository --repository-name nginx-base --region $AWS_DEFAULT_REGION || true
      - aws ecr create-repository --repository-name $REPOSITORY_NAME --region $AWS_DEFAULT_REGION || true
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPOSITORY_NAME
      - echo "Logging in to ECR $ECR_URI"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $REPOSITORY_NAME -f Dockerfile.nginx .
      - docker tag $REPOSITORY_NAME:latest $ECR_URI:latest

  post_build:
    commands:
      - echo "Pushing to ECR $ECR_URI"
      - docker push $ECR_URI:latest

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - dist/**/*
