version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 570753532112.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=570753532112.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo REPOSITORY_URI=$REPOSITORY_URI
      - echo IMAGE_TAG=$IMAGE_TAG

  build:
    commands:
      - echo Build started on `date`
      - echo Building Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Updating Kubernetes deployment...
      - aws eks update-kubeconfig --region ap-south-1 --name brain-tasks-cluster
      - kubectl set image deployment/brain-tasks-app brain-tasks-container=$REPOSITORY_URI:$IMAGE_TAG
      - kubectl rollout status deployment/brain-tasks-app

artifacts:
  files:
    - imagedefinitions.json
