version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo install...
  build:
    commands:
      - echo build...
      - npm ci
      - npm run build

artifacts:
  files:
    - appspec.yml
    - scripts/**
    - dist/**               # your built static files
    - Dockerfile*           # if you want Dockerfile in artifact
  discard-paths: no
