version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region ap-south-1)
      - IMAGE_TAG=$(date +%Y%m%d%H%M%S)
      - echo IMAGE_TAG=$IMAGE_TAG
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Updating kubeconfig...
      - aws eks update-kubeconfig --region ap-south-1 --name brain-tasks-cluster
      - echo Deploying to EKS...
      - kubectl set image deployment/brain-tasks-app brain-tasks-container=$REPOSITORY_URI:$IMAGE_TAG

artifacts:
  files:
    - '**/*'
