version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "INSTALL PHASE: nothing to install (we use prebuilt dist)"
  pre_build:
    commands:
      - echo "PRE_BUILD: nothing"
  build:
    commands:
      - echo "BUILD PHASE: skipping build; packaging repo files"

artifacts:
  files:
    - appspec.yml
    - scripts/** 
    - dist/** 
    - Dockerfile* 
    - buildspec.yml
  discard-paths: no
