
version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "ap-south-1"
    REPOSITORY_NAME: "brain-tasks-app"

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPOSITORY_NAME
      - echo "ECR_URI=$ECR_URI"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $REPOSITORY_NAME -f Dockerfile.nginx .
      - docker tag $REPOSITORY_NAME:latest $ECR_URI:latest

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $ECR_URI:latest
      - printf '[{"name":"brain-tasks-container","imageUri":"%s"}]' $ECR_URI:latest > imagedefinitions.json
      - echo "Build completed on $(date)"

artifacts:
  files:
    - imagedefinitions.json
    - appspec.yml
    - scripts/**/*
  discard-paths: no
